### ISSUE TITLE
Regarding the End product of this Project

### ISSUE THREAD

**Issue by Akhil-Sharma-26** [Vaurkhorov/liars-dice#1]
I want to get some clarification on how and what we are going to implement. Can you provide me with some future plans for this project (some design ideas or something like that)? How the product is going to look in the end? :+1: :smile:

**Comment by Vaurkhorov** [comment]
The design will stay simple. Right now I'm thinking that up to five players will be able to play, with each player getting their own separate window for looking at their dice, and it'll be implemented so that everyone is playing on the same device. The design will follow [this](https://www.egui.rs/) demo closely to start, and maybe change later.

**Comment by Akhil-Sharma-26** [comment]
> The design will stay simple. Right now, I'm thinking that up to five players will be able to play, with each player getting their own separate window for looking at their dice, and it'll be implemented so that everyone is playing on the same device. The design will closely follow [this](https://www.egui.rs/) demo to start and maybe change later.

Ok... That's a nice plan. How are five players going to play on the same device? Or Do you mean we are going to deploy it on a single device (in the testing phase) through which people can access it?

**Comment by Vaurkhorov** [comment]
Different windows on each player, only one window will work at a time, and will need to confirm that the intended player is accessing it. The idea's a work in progress still, so any other suggestions are welcome. It is intended to work on a single device, though.
